# Generated by Django 4.1.5 on 2023-08-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEcole', '0006_alter_user_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profil',
            field=models.ImageField(upload_to='images'),
        ),
    ]
